services:
  mongo:
    image: mongo:7.0
    container_name: mongo
    restart: always
    env_file:
      .env
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: fastapi
    restart: always
    env_file:
      .env
    ports:
      - "8000:8000"
    depends_on:
      - mongo

volumes:
  mongo_data:
